# -*- coding: utf-8 -*-
"""Tarea4_daa.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gJVUoqHT8dVeMCa41aC8limM36iZucch
"""

def ejemplo4(n):
  count = 0
  print("Nivel 1") # Para que imprima 3 operaciones puse un print en cada instrucción fuera del while
  i = n 
  print("Nivel 1") # Para que imprima 3 operaciones puse un print en cada instrucción fuera del while
  while i >= 1:
    count += 1
    i = i // 2
    print("Nivel 2")
  basura = 3 + 2
  print("Nivel 1") # Para que imprima 3 operaciones puse un print en cada instrucción fuera del while
  return count

print(ejemplo4(2), "\n")
print(ejemplo4(4), "\n")
print(ejemplo4(8), "\n")
print(ejemplo4(10), "\n")
print(ejemplo4(100), "\n")
print(ejemplo4(1000), "\n")
print(ejemplo4(10000), "\n")
print(ejemplo4(100000), "\n")
print(ejemplo4(1000000), "\n")